#!/bin/bash
sed -i "6cExec=mate-terminal -x sh cerrar_ambe_server.sh" /home/ORANGEPIpi/Desktop/Abrir_ambe_server.desktop
sed -i "7c Icon=/home/ORANGEPIpi/ORANGEPI/AMBER_SERVER_ON.png" /home/ORANGEPIpi/Desktop/Abrir_ambe_server.desktop
sed -i "10c Name[es_ES]=Cerrar AMBE SERVER" /home/ORANGEPIpi/Desktop/Abrir_ambe_server.desktop

puerto_router=$(awk "NR==11" /home/ORANGEPIpi/status.ini) 
puerto_modem=$(awk "NR==12" /home/ORANGEPIpi/status.ini)
cd /home/ORANGEPIpi/AMBEServer
sudo killall AMBEserver
sleep 5
mate-terminal -x ./AMBEserver -p $puerto_router -i $puerto_modem